version: '3.8'

services:
  backend:
    image: maxitrigo/micropayments:latest
    ports:
      - '80:3001'  # Backend escucha en el puerto 3001
    env_file:
      - .env
    command: npm run start:prod
    restart: always

  PAYMENTSDB:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    env_file:
      - .env

volumes:
  postgres-data:
